### ISSUE TITLE
Error with path detection

### ISSUE THREAD

**Issue by joetjen** [complyue/BunyanConsole#1]
First of I love the plugin. I am running on an Ubuntu desktop. Node is installed using NVM, bunyan is installed globally.

Since NVM is able to maintain several versions of node at once, all version specific paths (like node or binaries of globally packages installed under that specific version of node) are setup during initialization in the .bash_profile. Somehow the plugin seems not to be able to find the correct paths to neither bunyan nor node and to solve the problem is had to create hard links in /usr/local/bin for bunyan and node.

**Comment by complyue** [comment]
There exists a hack (https://github.com/complyue/BunyanConsole/blob/master/src/cyue/idea/plugins/bunyan/BunyanFilter.java#L20) to prefer some hard-coded locations, coz OSX will reset PATH env for PyCharm's executable (without /usr/local/bin in it). So if you have an executable /usr/local/bin/bunyan, it's surely be used anyway. Have you ever tried removing that one and see what happens? I'd hoped the fallback `return "bunyan";` there should work on Linux/Window.

**Comment by joetjen** [comment]
I had no links for `bunyan` and/or `node` in `/usr/local/bin` to begin with. After I installed the `bunyan` plugin I suddenly couldn't use the console anymore but instead got a typical Java Exception (NullPointer IIRC). After looking through the code and trying to locate the problem I noticed that for some reason the `bunyan` _executable_ was not found correctly, therefore I did `cd /usr/local/bin && ln -s $(which bunyan) bunyan` in my shell, after which I started to get error messages (through Java Exceptions) that `/usr/bin/env node` was not able to find `node`. After I did with node what I did with `bunyan` before everything worked fine.

**Comment by complyue** [comment]
just created ver 1.0.5, pls update to see if works for you.

**Comment by joetjen** [comment]
``` java
module.js:327
java.lang.NullPointerException
    at java.nio.file.Files.provider(Files.java:97)
    at java.nio.file.Files.readAttributes(Files.java:1737)
    at java.nio.file.Files.isDirectory(Files.java:2192)
    at cyue.idea.plugins.bunyan.PipeProcessing.convert(PipeProcessing.java:44)
    at cyue.idea.plugins.bunyan.BunyanFilter.applyFilter(BunyanFilter.java:110)
    at com.intellij.execution.filters.CompositeInputFilter$1.applyFilter(CompositeInputFilter.java:70)
    at com.intellij.execution.filters.CompositeInputFilter.applyFilter(CompositeInputFilter.java:48)
    at com.intellij.execution.impl.ConsoleViewImpl.print(ConsoleViewImpl.java:615)
    at com.intellij.execution.impl.ConsoleViewRunningState$1.onTextAvailable(ConsoleViewRunningState.java:43)
    at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:215)
    at com.sun.proxy.$Proxy14.onTextAvailable(Unknown Source)
    at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:189)
    at com.intellij.execution.process.ColoredProcessHandler.textAvailable(ColoredProcessHandler.java:92)
    at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:67)
    at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:134)
    at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:73)
    at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:56)
    at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:291)
    at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:198)
    at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:184)
    at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:104)
    at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:82)
    at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:160)
    at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:61)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    throw err;
```

**Comment by complyue** [comment]
1.0.6 will address the NPE, but I feel there're deeper causes preventing correct resolution from PATH env. There is hope that it may even work without successful resolution from my code, pls have a try anyway.

BTW does `module.js:` mean you are running WebStorm? For WebStorm, there is a [better solution ](http://stackoverflow.com/a/38718203/6394508) than this plugin.
