### ISSUE TITLE
On Windows 10 x64 it tries to use the shell script instead of the batch file.

### ISSUE THREAD

**Issue by aand18** [complyue/BunyanConsole#2]
On PHPStorm 2017.3.3 

On windows 10 x64 it tries to use the shell script instead of the batch file.

Indeed, `where bunyan` returns 
```
C:\Users\user.user\AppData\Roaming\npm\bunyan
C:\Users\user.user\AppData\Roaming\npm\bunyan.cmd
```
but I think it's wrong.

```
java.io.IOException: **Cannot run program "C:\Users\user.user\AppData\Roaming\npm\bunyan": CreateProcess error=193, %1 non è un'applicazione di Win32 valida**
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:528)
	at cyue.idea.plugins.bunyan.PipeProcessing.convert(PipeProcessing.java:48)
	at cyue.idea.plugins.bunyan.BunyanFilter.applyFilter(BunyanFilter.java:111)
	at com.intellij.execution.filters.CompositeInputFilter$1.applyFilter(CompositeInputFilter.java:72)
	at com.intellij.execution.filters.CompositeInputFilter.applyFilter(CompositeInputFilter.java:50)
	at com.intellij.execution.impl.ConsoleViewImpl.print(ConsoleViewImpl.java:583)
	at com.jetbrains.php.composer.actions.log.ComposerLogConsoleView.lambda$null$0(ComposerLogConsoleView.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.jetbrains.php.composer.actions.log.ComposerLogConsoleView.lambda$print$1(ComposerLogConsoleView.java:160)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: CreateProcess error=193, %1 non è un'applicazione di Win32 valida
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more
```

**Comment by complyue** [comment]
This plugin was origionally developed for PyCharm on OSX, so there's no test conducted against Windows so far. What program are you running spitting out bunyan log ?

Btw bunyan is losing its niche in python as the original [python-bunyan](https://github.com/Sagacify/logger-py) ( [my fork](https://github.com/complyue/python-bunyan) ) has deviated from bunyan format. So I have abandoned the adoption (development as well) of this plugin.
